export class cQuerysSQL {
  static getFacturaVenta = `
        SELECT 
            FV.NUMSERIE,
            FV.NUMFACTURA,
            FV.FECHA,
            FV.CODCLIENTE,
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 2), 2) TOTALNETO_USD, 
            C.NOMBRECLIENTE AS RAZONSOCIAL,
            C.NIF20,
            C.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASVENTA FV 
			LEFT JOIN ALBVENTACAB AVC ON FV.NUMSERIE = AVC.NUMSERIEFAC AND FV.NUMFACTURA = AVC.NUMFAC AND FV.N = AVC.NFAC
            LEFT JOIN CLIENTES C ON FV.CODCLIENTE = C.CODCLIENTE
        WHERE
            FV.NUMSERIE LIKE @SERIE + '%'
            AND FV.NUMFACTURA = @NUMERO
			AND FV.N = 'B' 
    `;

  static getFacturasVentas = `
        SELECT 
            FV.NUMSERIE,
            FV.NUMFACTURA,
            FV.FECHA,
            FV.CODCLIENTE,
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 2), 2) TOTALNETO_USD, 
            C.NOMBRECLIENTE,
            C.NIF20,
            C.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASVENTA FV 
			LEFT JOIN ALBVENTACAB AVC ON FV.NUMSERIE = AVC.NUMSERIEFAC AND FV.NUMFACTURA = AVC.NUMFAC AND FV.N = AVC.NFAC
            LEFT JOIN CLIENTES C ON FV.CODCLIENTE = C.CODCLIENTE
        WHERE
            FV.N = 'B'
        ORDER BY 
            FV.NUMSERIE DESC,
            FV.NUMFACTURA DESC
        OFFSET @OFFSET ROWS 
        FETCH NEXT @LIMIT ROWS ONLY
    `;

  static getCountFacturasVentas = `
        SELECT COUNT(*) as total FROM FACTURASVENTA WHERE N = 'B'
    `;

  static getDetalleFacturaVenta = `
        SELECT 
            AVL.CODARTICULO,
			MAX(AVL.DESCRIPCION) AS DESCRIPCION, 
            ROUND((RIP.F_GET_COTIZACION_RIP(MAX(PRECIO), MAX(AVC.FECHA), MAX(AVC.FACTORMONEDA), MAX(AVC.CODMONEDA), 1 )), 2) PRECIOBS,
            ROUND((RIP.F_GET_COTIZACION_RIP(MAX(PRECIO), MAX(AVC.FECHA), MAX(AVC.FACTORMONEDA), MAX(AVC.CODMONEDA), 2 )), 2) PRECIOUSD,
            MAX(AVL.REFERENCIA) AS REFERENCIA,
			MAX(AVL.CODALMACEN) AS ALMACEN, 
			MIN(AL.TALLA) AS TALLA, 
			MIN(AL.COLOR) AS COLOR,
            SUM(AVL.UNIDADESTOTAL) AS CANTIDAD
        FROM 
            ALBVENTALIN AVL
            INNER JOIN ALBVENTACAB AVC ON AVL.NUMSERIE = AVC.NUMSERIE AND AVL.NUMALBARAN = AVC.NUMALBARAN AND AVL.N = AVC.N
            LEFT JOIN ARTICULOSLIN AL ON AVL.CODARTICULO = AL.CODARTICULO AND AVL.TALLA = AL.TALLA AND AVL.COLOR = AL.COLOR
            LEFT JOIN ARTICULOS A ON AVL.CODARTICULO = A.CODARTICULO
        WHERE
            AVC.NUMSERIEFAC LIKE @SERIE + '%'
            AND AVC.NUMFAC = @NUMERO
            AND AVC.NFAC = 'B'
		GROUP BY 
			AVL.CODARTICULO
    `;

  static getFacturaCompra = `
        SELECT 
            FC.NUMSERIE, 
            FC.NUMFACTURA, 
            ACC.NUMALBARAN,
            ACC.FECHAALBARAN,
            FC.CODPROVEEDOR,
            ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, ACC.FECHAALBARAN, FC.FACTORMONEDA, FC.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, ACC.FECHAALBARAN, FC.FACTORMONEDA, FC.CODMONEDA, 2), 2) TOTALNETO_USD, 
            P.NOMPROVEEDOR, 
            P.NIF20, 
            P.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASCOMPRA FC
            LEFT JOIN PROVEEDORES P ON FC.CODPROVEEDOR = P.CODPROVEEDOR
            INNER JOIN ALBCOMPRACAB ACC ON FC.NUMSERIE = ACC.NUMSERIEFAC AND FC.NUMFACTURA = ACC.NUMFAC AND FC.N = ACC.N
        WHERE 
            FC.NUMSERIE = @SERIE      
            AND FC.NUMFACTURA = @NUMERO
            AND FC.N = 'B'
    `;

  static getFacturasCompras = `
        SELECT 
            FC.NUMSERIE, 
            FC.NUMFACTURA, 
            ACC.NUMALBARAN,
            ACC.FECHAALBARAN,
            FC.CODPROVEEDOR,
            ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, ACC.FECHAALBARAN, FC.FACTORMONEDA, FC.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, ACC.FECHAALBARAN, FC.FACTORMONEDA, FC.CODMONEDA, 2), 2) TOTALNETO_USD, 
            P.NOMPROVEEDOR, 
            P.NIF20, 
            P.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASCOMPRA FC
            LEFT JOIN PROVEEDORES P ON FC.CODPROVEEDOR = P.CODPROVEEDOR
            INNER JOIN ALBCOMPRACAB ACC ON FC.NUMSERIE = ACC.NUMSERIEFAC AND FC.NUMFACTURA = ACC.NUMFAC AND FC.N = ACC.N
        WHERE 
            FC.N = 'B'
        ORDER BY 
            FC.NUMSERIE DESC,
            FC.NUMFACTURA DESC
        OFFSET @OFFSET ROWS 
        FETCH NEXT @LIMIT ROWS ONLY
    `;

  static getCountFacturasCompras = `
        SELECT COUNT(*) as total FROM FACTURASCOMPRA WHERE N = 'B'
    `;
  static getDetalleFacturaCompra = `
        SELECT 
            ACL.CODARTICULO, 
            MAX(ACL.DESCRIPCION) AS DESCRIPCION, 
            ROUND((RIP.F_GET_COTIZACION_RIP(MAX(PRECIO), MAX(ACC.FECHAALBARAN), MAX(ACC.FACTORMONEDA), MAX(ACC.CODMONEDA), 1 )), 2) PRECIOBS,
            ROUND((RIP.F_GET_COTIZACION_RIP(MAX(PRECIO), MAX(ACC.FECHAALBARAN), MAX(ACC.FACTORMONEDA), MAX(ACC.CODMONEDA), 2 )), 2) PRECIOUSD,
            MAX(ACL.REFERENCIA) AS REFERENCIA,
            MAX(ACL.CODALMACEN) AS ALMACEN, 
            MAX(ACL.TALLA) AS TALLA, 
            MAX(ACL.COLOR) AS COLOR,
            SUM(ACL.UNIDADESTOTAL) AS CANTIDAD
        FROM 
            ALBCOMPRALIN ACL
            INNER JOIN ALBCOMPRACAB ACC ON ACL.NUMSERIE = ACC.NUMSERIE AND ACL.NUMALBARAN = ACC.NUMALBARAN AND ACL.N = ACC.N
        WHERE 
            ACC.NUMSERIEFAC LIKE @SERIE + '%' 
            AND ACC.NUMFAC = @NUMERO 
            AND ACC.NFAC = 'B'
        GROUP BY 
            ACL.CODARTICULO
    `;

  static getClientes = `
        SELECT 
            C.*,
            FP.CODSICM AS CODSICM
        FROM 
            CLIENTES C
            LEFT JOIN FARMAPATRIACLIENTES FP ON C.CODCLIENTE = FP.CODCLIENTE
        ORDER BY 
            C.CODCLIENTE 
            OFFSET @OFFSET ROWS FETCH NEXT @LIMIT ROWS ONLY
    `;

  static getCliente = `
    SELECT 
	C.*,
	FP.CODSICM AS CODSICM
FROM 
	CLIENTES C
	LEFT JOIN FARMAPATRIACLIENTES FP ON C.CODCLIENTE = FP.CODCLIENTE
WHERE 
	C.CODCLIENTE = @CODCLIENTE
    `;

  static getCountClientes = `SELECT COUNT(*) as total FROM CLIENTES`;

  static getProveedores = `
    SELECT 
        P.*,
        FP.CODSICM AS CODSICM
    FROM 
        PROVEEDORES P
        LEFT JOIN FARMAPATRIAPROVEEDORES FP ON P.CODPROVEEDOR = FP.CODPROVEEDOR
    ORDER BY 
        P.CODPROVEEDOR 
        OFFSET @OFFSET ROWS FETCH NEXT @LIMIT ROWS ONLY
  `;

  static getCountProveedores = `SELECT COUNT(*) as total FROM PROVEEDORES`;

  static getProveedor = `SELECT * FROM PROVEEDORES WHERE CODPROVEEDOR = @CODPROVEEDOR`;

  static getArticulos = `
    SELECT 
        ART.CODARTICULO,
        AFP.CODSICM, 
        ART.DESCRIPCION,
        (ISNULL(AFP.DESCSICM, '')) AS DESCRIPCIONSCIM,
        ART.REFPROVEEDOR,
        ACL.CODBARRAS
    FROM 
        ARTICULOS ART 
        LEFT JOIN ARTICULOSLIN ACL ON ART.CODARTICULO = ACL.CODARTICULO
        LEFT JOIN  ARTICULOSFARMAPATRIA AFP ON ART.CODARTICULO = AFP.CODARTICULO
    WHERE 
        ACL.CODBARRAS <> ''
        AND ACL.TALLA = '.'
        AND ACL.COLOR = '.'
        AND (@BUSQUEDA IS NULL OR ART.DESCRIPCION LIKE '%' + @BUSQUEDA + '%' OR ART.CODARTICULO = @BUSQUEDA)
    ORDER BY
        ART.DESCRIPCION ASC 
    OFFSET @OFFSET ROWS 
    FETCH NEXT @LIMIT ROWS ONLY
  `;

  static getArticulosSinVincular = `
    SELECT TOP (@LIMIT)
        A.CODARTICULO, 
        A.DESCRIPCION, 
        A.REFPROVEEDOR AS REFERENCIA
    FROM 
        ARTICULOS A
        LEFT JOIN ARTICULOSFARMAPATRIA AFP ON A.CODARTICULO = AFP.CODARTICULO
    WHERE 
        AFP.CODARTICULO IS NULL      
        AND A.REFPROVEEDOR IS NOT NULL  
        AND LEN(A.REFPROVEEDOR) > 5  
    ORDER BY 
        A.CODARTICULO ASC
  `;

  static getArticuloDetalle = `
    SELECT 
        ART.CODARTICULO,
        AFP.CODSICM, 
        ACL.TALLA AS TALLA,
        ACL.COLOR AS COLOR,
        ISNULL(DPTO.DESCRIPCION, '') AS DEPARTAMENTO,
        ISNULL(SEC.DESCRIPCION, '') AS SECCION, 
        ISNULL(FAM.DESCRIPCION, '') FAMILIA,
        ISNULL(SFA.DESCRIPCION, '') SUBFAMILIA,
        ISNULL(MC.DESCRIPCION, '') MARCA,
        ART.DESCRIPCION,
        (ISNULL(AFP.DESCSICM, '')) AS DESCRIPCIONSCIM,
        ART.REFPROVEEDOR,
        ACL.CODBARRAS, 
        ACL.PRECIOULTCOMPRA,
        ISNULL(PV.PNETO, 0) AS PNETO,
        ISNULL(ST.STOCK, 0) AS STOCK
    FROM 
        ARTICULOS ART 
        LEFT JOIN ARTICULOSLIN ACL ON ART.CODARTICULO = ACL.CODARTICULO
        LEFT JOIN  ARTICULOSFARMAPATRIA AFP ON ART.CODARTICULO = AFP.CODARTICULO
        LEFT JOIN PRECIOSVENTA PV ON ART.CODARTICULO = PV.CODARTICULO AND ACL.TALLA = PV.TALLA AND ACL.COLOR = PV.COLOR AND PV.IDTARIFAV = 2
        LEFT JOIN DEPARTAMENTO DPTO ON ART.DPTO = DPTO.NUMDPTO
        LEFT JOIN SECCIONES SEC ON ART.SECCION = SEC.NUMSECCION
        LEFT JOIN FAMILIAS FAM ON ART.FAMILIA = FAM.NUMFAMILIA
        LEFT JOIN SUBFAMILIAS SFA ON ART.SUBFAMILIA = SFA.NUMSUBFAMILIA
        LEFT JOIN MARCA MC ON ART.MARCA = MC.CODMARCA
        LEFT JOIN STOCKS ST ON ART.CODARTICULO = ST.CODARTICULO AND ST.TALLA = ACL.TALLA AND ST.COLOR = ACL.COLOR
    WHERE 
        ACL.CODBARRAS <> ''
        AND ACL.TALLA = '.'
        AND ACL.COLOR = '.'
        AND ART.CODARTICULO = @CODARTICULO
        AND ST.CODALMACEN = @ALMACEN
  `;

  static contarArticulos = `
    SELECT COUNT(*) as total
    FROM ARTICULOS 
    WHERE (@BUSQUEDA IS NULL OR DESCRIPCION LIKE '%' + @BUSQUEDA + '%' OR CODARTICULO = @BUSQUEDA)
  `;

  static mapearArticulos = `
    MERGE ARTICULOSFARMAPATRIA AS TARGET
    USING (SELECT @CODARTICULO AS CODARTICULO) AS SOURCE
    ON (TARGET.CODARTICULO = SOURCE.CODARTICULO)
    WHEN MATCHED THEN
        UPDATE SET 
            CODSICM = @CODIGO_SICM,
            DESCSICM = @DESC_GOBIERNO,
            ULTACTUALIZACION = GETDATE()
    WHEN NOT MATCHED 
        THEN INSERT (CODARTICULO, CODSICM, DESCSICM) 
        VALUES (@CODARTICULO, @CODIGO_SICM, @DESC_GOBIERNO);
  `;

  static getClientesSinMapear = `
    SELECT TOP (@LIMIT)
        C.CODCLIENTE, 
        C.NOMBRECLIENTE,
        C.NIF20, 
        REPLACE(REPLACE(C.NIF20, '-',''), '.','') AS FORMATRIF,
        C.CIF
    FROM 
        CLIENTES C 
        LEFT JOIN FARMAPATRIACLIENTES FPC ON C.CODCLIENTE = FPC.CODCLIENTE
    WHERE
        FPC.CODCLIENTE IS NULL
        AND LEN(C.NIF20) > 5 
  `;

  static insertarGuia = `
    INSERT INTO FARMAPATRIAGUIAS ( NUMGUIASICM, SERIEFAC, NUMFAC, CODCLIENTE, ESTATUS )
    VALUES (@GUIA, @SERIE, @NUMERO, @CLIENTE, @ESTATUS)
  `;

  static insertarMapeoCliente = `
    MERGE FARMAPATRIACLIENTES AS TARGET 
    USING (SELECT @RIF AS RIFCLIENTE) AS SOURCE 
    ON (TARGET.RIFCLIENTE = SOURCE.RIFCLIENTE)
    WHEN MATCHED THEN
        UPDATE SET CODCLIENTE = @CODIGO, CODSICM = @SICM, NOMBRECLIENTE = @NOMBRE, ESTATUS = @ESTATUS
    WHEN NOT MATCHED THEN 
        INSERT (CODCLIENTE, RIFCLIENTE, CODSICM, NOMBRECLIENTE, ESTATUS)
	    VALUES (@CODIGO, @RIF, @SICM, @NOMBRE, @ESTATUS); 
  `;

  static getProveedoresSinMapear = `
    SELECT TOP (@LIMIT)
        P.CODPROVEEDOR, 
        P.NOMPROVEEDOR,
        P.NIF20, 
        REPLACE(REPLACE(P.NIF20, '-',''), '.','') AS FORMATRIF,
        P.CIF
    FROM 
        PROVEEDORES P 
        LEFT JOIN FARMAPATRIAPROVEEDORES FPP ON P.CODPROVEEDOR = FPP.CODPROVEEDOR
    WHERE
        FPP.CODPROVEEDOR IS NULL
        AND LEN(P.NIF20) > 5 
  `;

  static insertarMapeoProveedor = `
    MERGE FARMAPATRIAPROVEEDORES AS TARGET 
    USING (SELECT @RIF AS RIFPROVEEDOR) AS SOURCE 
    ON (TARGET.RIFPROVEEDOR = SOURCE.RIFPROVEEDOR)
    WHEN MATCHED THEN
        UPDATE SET CODPROVEEDOR = @CODIGO, CODSICM = @SICM, NOMPROVEEDOR = @NOMBRE, ESTATUS = @ESTATUS
    WHEN NOT MATCHED THEN 
        INSERT (CODPROVEEDOR, RIFPROVEEDOR, CODSICM, NOMPROVEEDOR, ESTATUS)
	    VALUES (@CODIGO, @RIF, @SICM, @NOMBRE, @ESTATUS); 
  `;

  static obtenerClienteFP = `
    SELECT
        *
    FROM 
        FARMAPATRIACLIENTES
    WHERE 
        REPLACE(REPLACE(RIFCLIENTE, '-',''), '.','') = REPLACE(REPLACE(@RIF, '-',''), '.','')
  `;

  static validarArticuloFP = `
    SELECT CODSICM FROM ARTICULOSFARMAPATRIA WHERE CODARTICULO = @CODARTICULO 
  `;
}
