export class cQuerysSQL {
  static getFacturaVenta = `
         SELECT 
            FV.NUMSERIE,
            FV.NUMFACTURA,
            FV.FECHA,
            FV.CODCLIENTE,
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FV.TOTALNETO, FV.FECHA, FV.FACTORMONEDA, FV.CODMONEDA, 2), 2) TOTALNETO_USD, 
            C.NOMBRECLIENTE AS RAZONSOCIAL,
            C.NIF20,
            C.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASVENTA FV 
			LEFT JOIN ALBVENTACAB AVC ON FV.NUMSERIE = AVC.NUMSERIEFAC AND FV.NUMFACTURA = AVC.NUMFAC AND FV.N = AVC.NFAC
            LEFT JOIN CLIENTES C ON FV.CODCLIENTE = C.CODCLIENTE
        WHERE
            FV.NUMSERIE LIKE @SERIE + '%'
            AND FV.NUMFACTURA = @NUMERO
			AND FV.N = 'B' 
    `;

  static getDetalleFacturaVenta = `
        SELECT 
            AVL.CODARTICULO,
			MAX(AVL.DESCRIPCION) AS DESCRIPCION, 
            MAX(AVL.PRECIO) AS PRECIO,
            MAX(AVL.REFERENCIA) AS REFERENCIA,
			MAX(AVL.CODALMACEN) AS ALMACEN, 
			MIN(AL.TALLA) AS TALLA, 
			MIN(AL.COLOR) AS COLOR,
            SUM(AVL.UNIDADESTOTAL) AS CANTIDAD
        FROM 
            ALBVENTALIN AVL
            INNER JOIN ALBVENTACAB AVC ON AVL.NUMSERIE = AVC.NUMSERIE AND AVL.NUMALBARAN = AVC.NUMALBARAN AND AVL.N = AVC.N
            LEFT JOIN ARTICULOSLIN AL ON AVL.CODARTICULO = AL.CODARTICULO AND AVL.TALLA = AL.TALLA AND AVL.COLOR = AL.COLOR
            LEFT JOIN ARTICULOS A ON AVL.CODARTICULO = A.CODARTICULO
        WHERE
            AVC.NUMSERIEFAC LIKE @SERIE + '%'
            AND AVC.NUMFAC = @NUMERO
            AND AVC.NFAC = 'B'
		GROUP BY 
			AVL.CODARTICULO
    `;

  static getFacturaCompra = `
        SELECT 
            FC.NUMSERIE, 
            FC.NUMFACTURA, 
            ACC.NUMALBARAN,
            ACC.FECHAALBARAN,
            FC.CODPROVEEDOR,
            ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, FC.FECHA, FC.FACTORMONEDA, FC.CODMONEDA, 1), 2) TOTALNETO_BS, 
			ROUND(rip.F_GET_COTIZACION_RIP(FC.TOTALNETO, FC.FECHA, FC.FACTORMONEDA, FC.CODMONEDA, 2), 2) TOTALNETO_USD, 
            P.NOMPROVEEDOR, 
            P.NIF20, 
            P.DIRECCION1,
            NULL AS CODIGO_SICM
        FROM 
            FACTURASCOMPRA FC
            LEFT JOIN PROVEEDORES P ON FC.CODPROVEEDOR = P.CODPROVEEDOR
            INNER JOIN ALBCOMPRACAB ACC ON FC.NUMSERIE = ACC.NUMSERIEFAC AND FC.NUMFACTURA = ACC.NUMFAC AND FC.N = ACC.N
        WHERE 
            FC.NUMSERIE LIKE @SERIE + '%' 
            AND FC.NUMFACTURA = @NUMERO 
            AND FC.N = 'B'
    `;

  static getDetalleFacturaCompra = `
        SELECT 
            ACL.CODARTICULO, 
            MAX(ACL.DESCRIPCION) AS DESCRIPCION, 
            MAX(ACL.PRECIO) AS PRECIO, 
            MAX(ACL.REFERENCIA) AS REFERENCIA,
            MAX(ACL.CODALMACEN) AS ALMACEN, 
            MAX(ACL.TALLA) AS TALLA, 
            MAX(ACL.COLOR) AS COLOR,
            SUM(ACL.UNIDADESTOTAL) AS CANTIDAD
        FROM 
            ALBCOMPRALIN ACL
            INNER JOIN ALBCOMPRACAB ACC ON ACL.NUMSERIE = ACC.NUMSERIE AND ACL.NUMALBARAN = ACC.NUMALBARAN AND ACL.N = ACC.N
        WHERE 
            ACC.NUMSERIEFAC LIKE @SERIE + '%' 
            AND ACC.NUMFAC = @NUMERO 
            AND ACC.NFAC = 'B'
        GROUP BY 
            ACL.CODARTICULO
    `;

  static getClientes = `SELECT * FROM CLIENTES ORDER BY CODCLIENTE OFFSET @OFFSET ROWS FETCH NEXT @LIMIT ROWS ONLY`;

  static getCliente = `SELECT * FROM CLIENTES WHERE CODCLIENTE = @CODCLIENTE`;

  static getCountClientes = `SELECT COUNT(*) as total FROM CLIENTES`;

  static getProveedores = `SELECT * FROM PROVEEDORES ORDER BY CODPROVEEDOR OFFSET @OFFSET ROWS FETCH NEXT @LIMIT ROWS ONLY`;

  static getCountProveedores = `SELECT COUNT(*) as total FROM PROVEEDORES`;

  static getProveedor = `SELECT * FROM PROVEEDORES WHERE CODPROVEEDOR = @CODPROVEEDOR`;
}
